site_name: AIoD Python SDK
site_url: https://aiondemand.github.io/aiondemand
repo_url: https://www.github.com/aiondemand/aiondemand
repo_name: aiondemand

theme:
  name: material
  logo: images/secondary-neg-white-25p.webp
  features:
    - content.code.copy
  font:
    text: 'Montserrat'
  palette:
    scheme: 'aiod'
extra_css:
  - stylesheets/extra.css

nav:
  - Introduction: 'README.md'
  - notebook: 'example.ipynb'
  - API Reference:
      - 'api/case_studies.md'
      - 'api/computational_assets.md'
      - 'api/contacts.md'
      - 'api/datasets.md'
      - 'api/educational_resources.md'
      - 'api/events.md'
      - 'api/experiments.md'
      - 'api/ml_models.md'
      - 'api/news.md'
      - 'api/organisations.md'
      - 'api/persons.md'
      - 'api/platforms.md'
      - 'api/projects.md'
      - 'api/publications.md'
      - 'api/services.md'
      - 'api/teams.md'
  - 'changelog.md'
  - 'contributing.md'
  - 'conduct.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
- search
- privacy
- asset-type-replacer 
- mkdocs-jupyter:
    # TODO: when we can configure aiod, we should start running notebooks
    # execute: true
    # allow_errors: false
    ignore:
      - "*.py"
    include_source: True
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: false
          filters: ["!^_"]
          extensions:
          - docs/tools/griffe_extensions.py:
              modules:
              - aiod
              - aiod.resources.case_studies
              - aiod.resources.computational_assets
              - aiod.resources.contacts
              - aiod.resources.datasets
              - aiod.resources.educational_resources
              - aiod.resources.events
              - aiod.resources.experiments
              - aiod.resources.ml_models
              - aiod.resources.news
              - aiod.resources.organisations
              - aiod.resources.persons
              - aiod.resources.platforms
              - aiod.resources.projects
              - aiod.resources.publications
              - aiod.resources.services
              - aiod.resources.teams

