[project]
name = "aiondemand"
version = "0.0.1"
description = "Python SDK for the AIoD metadata catalogue"
authors = [
  { name = "Jean Matias", email = "smatias.jean@gmail.com" },
  { name = "Pieter Gijsbers", email = "p.gijsbers@tue.nl" },
]

readme = "docs/README.md"

requires-python = ">=3.11"

dependencies = ["aiohttp", "asyncio", "pandas", "python-keycloak", "requests"]

[project.optional-dependencies]
dev = ["pre-commit", "responses", "aioresponses", "pytest", "pytest-asyncio"]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.1"
version_files = ["pyproject.toml:version", "src/aiod/__version__.py"]
