[project]
name = "aiod-sdk"
version = "0.1.0"
description = "SDK for the AIoD API"
authors = [
    {name = "Jean Matias", "email" = "<smatias.jean@gmail.com>"},
]
license = "MIT License"
readme = "README.md"

dependencies = []

[project.optional-dependencies]
python = "^3.11"
dev = []


